name: With cached workspace

runs:
  using: composite

  steps:
    - name: Set up cache
      id: cache-workspace
      uses: actions/cache@v4
      with:
        path: ./
        key: workspace-${{ github.sha }}
