name: Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:
  pull_request: {}

jobs:
  setup:
    name: Set up
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [x86_64]

    steps:
      - name: Check out source code
        uses: actions/checkout@v4

      - name: Setup node
        uses: ./.github/actions/setup-node

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies

      - name: Build core-api
        run: npm run build:core-api

      - name: Set up cache
        id: cache-workspace
        uses: actions/cache@v4
        with:
          path: ./dist
          key: workspace-${{ github.run_number }}

  build_push:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Check out source code
        uses: actions/checkout@v4

      - name: Download cache
        id: cache-workspace
        uses: actions/cache@v3
        with:
          path: ./dist
          key: workspace-${{ github.run_number }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: vsezol/space-drive-visualizer
          tags: type=raw,value=latest

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./apps/core-api/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
