name: Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  setup:
    name: Set up
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v4

      - name: Setup node
        uses: ./.github/actions/setup-node

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies

      - name: Build core-api
        run: npm run build:core-api

      - name: Set up cache
        id: cache-workspace
        uses: actions/cache@v4
        with:
          path: ./dist
          key: workspace-${{ github.run_number }}

  build_push:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Check out source code
        uses: actions/checkout@v4

      - name: Download cache
        id: cache-workspace
        uses: actions/cache@v4
        with:
          path: ./dist
          key: workspace-${{ github.run_number }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./apps/core-api/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: vsezol/space-drive-visualizer:latest
